[package]
name = "raylib_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
rand = "0.8.5"
raylib = "3.7.0"
simplelog = "0.12.1"
